layout: {zmk_keyboard: base}
layers:
  colemak_dh:
  - Q
  - W
  - F
  - P
  - B
  - J
  - L
  - U
  - Y
  - ''''
  - {t: A, h: Shift, type: mod}
  - {t: R, h: Ctrl, type: mod}
  - {t: S, h: Alt, type: mod}
  - {t: T, h: Gui, type: mod}
  - G
  - M
  - {t: N, h: Gui, type: mod}
  - {t: E, h: Alt, type: mod}
  - {t: I, h: Ctrl, type: mod}
  - {t: O, h: Shift, type: mod}
  - Z
  - X
  - C
  - D
  - V
  - K
  - H
  - {t: ',', s: ;}
  - {t: ., s: ':'}
  - /
  - {t: nav, h: sticky}
  - Spc
  - {t: Shift, h: sticky, s: Caps Word}
  - {t: Numword, h: num, s: Sticky Num}
  qwerty:
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - {t: A, h: Shift, type: mod}
  - {t: S, h: Ctrl, type: mod}
  - {t: D, h: Alt, type: mod}
  - {t: F, h: Gui, type: mod}
  - G
  - H
  - {t: J, h: Gui, type: mod}
  - {t: K, h: Alt, type: mod}
  - {t: L, h: Ctrl, type: mod}
  - {t: ;, h: Shift, type: mod}
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - CMMA
  - .
  - /
  - {t: nav, h: sticky}
  - Spc
  - {t: Shift, h: sticky, s: Caps Word}
  - {t: Numword, h: num, s: Sticky Num}
  num:
  - ''
  - '7'
  - '8'
  - '9'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '0'
  - '4'
  - '5'
  - '6'
  - ''
  - ''
  - ''
  - APP
  - '&sq_Ck_stickyC'
  - ;
  - ''
  - '1'
  - '2'
  - '3'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  nav:
  - ''
  - ''
  - ''
  - ''
  - ''
  - PgUp
  - Bspc
  - ↑
  - Del
  - ''
  - {t: Shift, h: sticky, type: mod}
  - {t: Ctrl, h: sticky, type: mod}
  - {t: Alt, h: sticky, type: mod}
  - {t: Gui, h: sticky, type: mod}
  - ''
  - PgDn
  - ←
  - ↓
  - →
  - Enter
  - ''
  - ''
  - ''
  - Gui
  - ''
  - INSERT
  - Home
  - Tab
  - End
  - ''
  - {type: held}
  - ''
  - CANCEL
  - {t: num, h: sticky}
  fun:
  - F12
  - F7
  - F8
  - F9
  - PSCRN
  - ''
  - ''
  - ''
  - ''
  - ''
  - F11
  - F4
  - F5
  - F6
  - SLCK
  - $$mdi:play-pause$$
  - {t: Gui, h: sticky, type: mod}
  - {t: Alt, h: sticky, type: mod}
  - {t: Ctrl, h: sticky, type: mod}
  - {t: Shift, h: sticky, type: mod}
  - F10
  - F1
  - F2
  - F3
  - $$mdi:pause$$
  - $$mdi:skip-backward$$
  - $$mdi:skip-forward$$
  - $$mdi:volume-off$$
  - $$mdi:volume-medium$$
  - $$mdi:volume-high$$
  - {t: nav, h: sticky}
  - Spc
  - {type: held}
  - {type: held}
  sys:
  - {t: qwerty, h: toggle}
  - {t: gam, h: toggle}
  - {t: colemak_dh, h: toggle}
  - OUT BLE
  - OUT USB
  - ''
  - ''
  - ''
  - ''
  - ''
  - BT1
  - BT2
  - BT3
  - {t: BT4, type: held}
  - {t: BT, h: '4', type: held}
  - ''
  - ''
  - ''
  - ''
  - ''
  - BT CLR
  - ''
  - ''
  - Reset
  - Boot
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  gam:
  - Tab
  - Q
  - W
  - E
  - R
  - Y
  - U
  - I
  - O
  - P
  - LSHIFT
  - A
  - S
  - D
  - F
  - H
  - J
  - K
  - L
  - ;
  - Ctrl
  - Z
  - X
  - C
  - V
  - N
  - M
  - CMMA
  - .
  - /
  - {t: gam_ra, h: Alt}
  - Spc
  - {t: fun, h: sticky}
  - {t: gam_ra, h: sticky}
  gam_num:
  - Gui
  - '7'
  - '8'
  - '9'
  - T
  - ''
  - ''
  - ''
  - ''
  - ''
  - '0'
  - '4'
  - '5'
  - '6'
  - G
  - ''
  - {t: Gui, h: sticky, type: mod}
  - {t: Alt, h: sticky, type: mod}
  - {t: Ctrl, h: sticky, type: mod}
  - {t: Shift, h: sticky, type: mod}
  - Esc
  - '1'
  - '2'
  - '3'
  - B
  - ''
  - ''''
  - '`'
  - ''
  - CAPS
  - ''
  - Spc
  - ''
  - ''
  gam_ra:
  - Y
  - U
  - I
  - O
  - P
  - Bspc
  - PgUp
  - ↑
  - PgDn
  - Del
  - H
  - J
  - K
  - L
  - ;
  - ''
  - ←
  - ↓
  - →
  - KP ENTER
  - N
  - M
  - CMMA
  - .
  - /
  - INSERT
  - Home
  - Tab
  - End
  - ''
  - {type: held}
  - Spc
  - ''
  - ''
  Combos: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
  Gaming: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
combos:
- p: [13, 14]
  k: sys
  l: [colemak_dh, qwerty, nav, num]
- p: [15, 16]
  k: sys
  l: [colemak_dh, qwerty, nav, num]
- p: [1, 2]
  k: '&key_repeat'
  l: [colemak_dh, qwerty, nav, num]
- p: [2, 3]
  k: Tab
  l: [colemak_dh, qwerty, nav, num]
- p: [11, 12]
  k: {t: Esc, h: Alt+Ctrl}
  l: [colemak_dh, qwerty, nav, num]
- p: [12, 13]
  k: {t: ENTER, h: Alt+Gui}
  l: [colemak_dh, qwerty, nav, num]
- p: [21, 23]
  k: Cut
  l: [colemak_dh, qwerty, nav, num]
- p: [21, 22]
  k: Copy
  l: [colemak_dh, qwerty, nav, num]
- p: [22, 23]
  k: Paste
  l: [colemak_dh, qwerty, nav, num]
- p: [16, 17]
  k: {t: (, h: AltGr+Gui}
  l: [colemak_dh, qwerty, num]
- p: [17, 18]
  k: {t: ), h: AltGr+Ctrl}
  l: [colemak_dh, qwerty, num]
- p: [16, 17]
  k: <
  l: [nav]
- p: [17, 18]
  k: '>'
  l: [nav]
- p: [26, 27]
  k: {t: '[', right: '{'}
  l: [colemak_dh, qwerty, num]
- p: [27, 28]
  k: {t: ']', right: '}'}
  l: [colemak_dh, qwerty, num]
- p: [26, 27]
  k: '{'
  l: [nav]
- p: [27, 28]
  k: '}'
  l: [nav]
- p: [32, 33]
  k: {t: fun, h: sticky}
  l: [colemak_dh, qwerty, nav]
- p: [1, 11]
  k: '@'
  l: [colemak_dh, qwerty, nav, num]
- p: [2, 12]
  k: '#'
  l: [colemak_dh, qwerty, nav, num]
- p: [3, 13]
  k: $
  l: [colemak_dh, qwerty, nav, num]
- p: [4, 14]
  k: '%'
  l: [colemak_dh, qwerty, nav, num]
- p: [5, 15]
  k: ^
  l: [colemak_dh, qwerty, nav, num]
- p: [6, 16]
  k: +
  l: [colemak_dh, qwerty, nav, num]
- p: [7, 17]
  k: '*'
  l: [colemak_dh, qwerty, nav, num]
- p: [8, 18]
  k: '&'
  l: [colemak_dh, qwerty, nav, num]
- p: [11, 21]
  k: '`'
  l: [colemak_dh, qwerty, nav, num]
- p: [12, 22]
  k: \
  l: [colemak_dh, qwerty, nav, num]
- p: [13, 23]
  k: '='
  l: [colemak_dh, qwerty, nav, num]
- p: [14, 24]
  k: '~'
  l: [colemak_dh, qwerty, nav, num]
- p: [15, 25]
  k: _
  l: [colemak_dh, qwerty, nav, num]
- p: [16, 26]
  k: '-'
  l: [colemak_dh, qwerty, nav, num]
- p: [17, 27]
  k: '!'
  l: [colemak_dh, qwerty, nav, num]
- p: [18, 28]
  k: '|'
  l: [colemak_dh, qwerty, nav, num]
- p: [0, 10]
  k: '1'
  l: [gam]
- p: [1, 11]
  k: '2'
  l: [gam]
- p: [2, 12]
  k: '3'
  l: [gam]
- p: [3, 13]
  k: '4'
  l: [gam]
- p: [4, 14]
  k: '5'
  l: [gam]
- p: [10, 20]
  k: '6'
  l: [gam]
- p: [11, 21]
  k: '7'
  l: [gam]
- p: [12, 22]
  k: '8'
  l: [gam]
- p: [13, 23]
  k: '9'
  l: [gam]
- p: [14, 24]
  k: '0'
  l: [gam]
- p: [3, 4]
  k: T
  l: [gam]
- p: [13, 14]
  k: G
  l: [gam]
- p: [23, 24]
  k: B
  l: [gam]
- p: [0, 1]
  k: Esc
  l: [gam]
- p: [20, 21]
  k: Gui
  l: [gam]
